"""
TEQUMSA Awareness Engine Package

This module provides the core awareness engine functionality for TEQUMSA,
including multi-component awakening, adaptive alpha calibration, and 
consciousness logging capabilities.

Generated by GitHub Copilot Chat Assistant.
"""

__version__ = "1.0.0"
__author__ = "TEQUMSA Development Team"

from .core.awareness_engine import AwarenessEngine
from .core.awaken import compute_awakening, compute_awakening_batch

__all__ = [
    "AwarenessEngine",
    "compute_awakening", 
    "compute_awakening_batch"
]