"""
TEQUMSA Core Module

Contains the core awareness engine implementation including awakening functions,
engine class, and backend abstractions.

Generated by GitHub Copilot Chat Assistant.
"""

from .awaken import compute_awakening, compute_awakening_batch
from .awareness_engine import AwarenessEngine
from .backends import get_backend

__all__ = [
    "compute_awakening",
    "compute_awakening_batch", 
    "AwarenessEngine",
    "get_backend"
]